# Generated by Django 2.2.12 on 2020-04-20 06:00

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=200)),
                ('category_image', models.ImageField(upload_to='uploads/')),
                ('category_summary', models.TextField()),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 6, 0, 49, 359496), verbose_name='Date Published')),
                ('receipe_slug', models.CharField(default=1, max_length=200)),
                ('bookmarked_receipe', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('category_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category', verbose_name='Receipe')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 6, 0, 49, 361603))),
                ('active', models.BooleanField(default=False)),
                ('title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Receipe', verbose_name='comment')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
