# Generated by Django 2.2.12 on 2020-04-20 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200420_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='bookmarked_receipe',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 8, 49, 18, 178078)),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 8, 49, 18, 177407), verbose_name='Date Published'),
        ),
    ]
