# Generated by Django 2.2.12 on 2020-04-21 10:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20200420_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 10, 14, 10, 954180)),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 10, 14, 10, 952602), verbose_name='Date Published'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'receipe')},
        ),
    ]
